### ISSUE TITLE
simple example for seeing if data pump has stopped from cloud level

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/module-core-rql#24]
for example let's start with `esr` and the `wattwatchers` meters

basic rule
- run every 12 hours
- check each meter if not new data or has flatlined
- raise alert if above is true

see examples on read me

https://github.com/NubeIO/module-core-rql?tab=readme-ov-file#droplet-alarms

see other issue for reference 
https://github.com/NubeIO/module-core-rql/issues/22

**Comment by CanuckMarc** [comment]
Working on this in another issue.  To be implemented with meta-tags.
