### ISSUE TITLE
update wiki

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/module-core-rql#25]
## tags, meta tags

Add examples for calling by tags and meta tags

and use for calling 
- points
- histoires

## add an example of going through history data
Add an example of looping through history data

for example sum all the values

**Comment by enjuthulung** [comment]
hi @NubeDev updated wiki: https://github.com/NubeIO/module-core-rql/wiki/RQL-script-examples#3-histories-metricscountsumavgminmax
