### ISSUE TITLE
rules

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/module-core-rql#26]
# setup ping/check and raise alert for each offline host
- run every 1 hour
- only raise an later if ping fail count is >= 2

# lora rules

For each `host` that has a network of type `module-core-loraraw` we need to write 2x rules to generate alerts.

- run every 12 hour
- voltage threshold will be 3.8

Check voltage level and `lastOk`

- if voltage is `<` `3.8` we need to raise an alert
- also we need to check the `lastOk`  and if the time is more then 4 hours ago we need to raise an alert

```
let hostID = "hos_9287616811674038";

RQL.Result = RQL.GetPointsByModuleName(hostID, "module-core-loraraw");
```

![image](https://github.com/NubeIO/module-core-rql/assets/18637436/77676a54-a449-4036-9740-35466da23d76)

**Comment by CanuckMarc** [comment]
This will be done via meta-tags.  Working on this in a seperate issue.  Closing
